version: '3.2'
services:
  api:
    container_name: api
    build: ./API
    ports:
      - '8080:8080'
      - '9229:9229'
  db:
    container_name: db
    image: mongo:4.0.2
  dbGUI:
    container_name: dbGUI
    image: mongo-express:0.49
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
